[CICD] Fixes (same as prod branch)

diff --git a/.github/workflows/prod-delivery.yml b/.github/workflows/prod-delivery.yml
--- a/.github/workflows/prod-delivery.yml
+++ b/.github/workflows/prod-delivery.yml
@@ -45,9 +45,12 @@ jobs:
         run: cd Tools/RessourcesChecker/ && python3 main.py
 
   test-server:
-    name: '🔍 Application tests'
+    name: '🔍 Server tests'
     runs-on: ubuntu-latest
     steps:
+      - name: 'Checkout'
+        uses: actions/checkout@v4
+
       - name: 'Install PHP with mysqli extension'
         run: sudo apt-get update && sudo apt-get install php php-mysqli -y
 
@@ -295,18 +298,30 @@ jobs:
 
       - name: 'Setup API App Store Connect'
         env:
+          KEY_PATH: ios/build/private_keys
           SEND_KEY: ${{ secrets.APPLE_API_APP_STORE_CONNECT_SEND_KEY }}
-          KEY_PATH: ~/.appstoreconnect/private_keys/
           KEY_CONTENT: ${{ secrets.APPLE_API_APP_STORE_CONNECT_AUTH_KEY }}
         run: |
           # Create directory
           mkdir -p $KEY_PATH
 
+          # Go to the ios directory
+          cd $KEY_PATH
+
           # Get key name (AuthKey_$SEND_KEY.p8)
-          KEY_NAME=AuthKey_$SEND_KEY.p8
+          KEY_NAME="AuthKey_$SEND_KEY.p8"
 
           # Import key from secrets
-          echo -n "$KEY_CONTENT" | base64 --decode > "$KEY_PATH$KEY_NAME"
+          echo -n "$KEY_CONTENT" | base64 --decode > $KEY_NAME
+
+          # Go back
+          cd -
+
+          # Print current directory
+          pwd
+
+          # Check if key is valid
+          ls -l $KEY_PATH/$KEY_NAME
 
       - name: 'Upload to App Store'
         env:
@@ -324,12 +339,23 @@ jobs:
             --apiIssuer "$ISSUER_ID" \
             --verbose
 
+          # Check if upload was successful
+          if [ $? -eq 0 ]; then
+            echo "Upload successful"
+          else
+            echo "Upload failed"
+            exit 1
+          fi
+
   notify-android:
     name: '📣 Notify Team - App Published 🤖'
     if: github.event.inputs.actions == 'both' || github.event.inputs.actions == 'android'
     runs-on: ubuntu-latest
     needs: delivery-android
     steps:
+      - name: 'Checkout repository'
+        uses: actions/checkout@v4
+
       - name: 'Install PHP with mysqli extension'
         run: sudo apt-get update && sudo apt-get install php php-mysqli -y
 
@@ -361,6 +387,9 @@ jobs:
     runs-on: ubuntu-latest
     needs: delivery-ios
     steps:
+      - name: 'Checkout repository'
+        uses: actions/checkout@v4
+
       - name: 'Install PHP with mysqli extension'
         run: sudo apt-get update && sudo apt-get install php php-mysqli -y
 
