[CICD] Update & update version script

diff --git a/.github/workflows/prod-delivery.yml b/.github/workflows/prod-delivery.yml
--- a/.github/workflows/prod-delivery.yml
+++ b/.github/workflows/prod-delivery.yml
@@ -17,6 +17,11 @@ on:
         required: true
         default: false
         type: boolean
+      apk-artifact:
+        description: 'Download apk artifact (only for android)'
+        required: false
+        default: false
+        type: boolean
 
 jobs:
   test-client:
@@ -67,32 +72,12 @@ jobs:
           '${{ secrets.DB_TEST_PASS }}' \
           '${{ vars.DB_TEST_NAME }}'
 
-  enable-test-account:
-    name: '🔑 Enable test account'
-    runs-on: ubuntu-latest
-    needs: [ test-client, test-server ]
-    steps:
-      - name: 'Checkout'
-        uses: actions/checkout@v4
-
-      - name: 'Install PHP with mysqli extension'
-        run: sudo apt-get update && sudo apt-get install php php-mysqli -y
-
-      - name: 'Enable test account'
-        run: |
-          php ./Tools/Maintenance/setTestAccount.php \
-          '${{ vars.DB_PROD_HOST }}' \
-          '${{ vars.DB_PROD_USER }}' \
-          '${{ secrets.DB_PROD_PASS }}' \
-          '${{ vars.DB_PROD_NAME }}' \
-          1
-
   build-android:
     name: '🏗️ Build application 🤖'
     if: github.event.inputs.actions == 'both' || github.event.inputs.actions == 'android'
     runs-on: ubuntu-latest
     container: reactnativecommunity/react-native-android
-    needs: enable-test-account
+    needs: [ test-client, test-server ]
     steps:
       - name: 'Checkout'
         uses: actions/checkout@v4
@@ -141,6 +126,32 @@ jobs:
           name: GameLife-prod-mapping.txt
           path: GameLife-prod-mapping.txt
 
+      - name: 'Download buildtool'
+        if: ${{ github.event.inputs.apk-artifact }}
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y wget unzip
+          wget -O bundletool.jar https://github.com/google/bundletool/releases/download/1.15.0/bundletool-all-1.15.0.jar
+
+      - name: 'Generate universal APK'
+        if: ${{ github.event.inputs.apk-artifact }}
+        run: |
+          java -jar ./bundletool.jar build-apks \
+            --bundle=GameLife-prod.aab \
+            --output=my_app.apks \
+            --mode=universal \
+            --ks=./android/app/gamelife.keystore \
+            --ks-key-alias=gameLifeAlias \
+            --ks-pass=file:./keystore
+          unzip -p my_app.apks universal.apk > GameLife-prod.apk
+
+      - name: 'Upload apk artifact'
+        if: ${{ github.event.inputs.apk-artifact }}
+        uses: actions/upload-artifact@v3
+        with:
+          name: GameLife-prod.apk
+          path: GameLife-prod.apk
+
   delivery-android:
     name: '📦 Continuous Delivery 🤖'
     if: (github.event.inputs.actions == 'both' || github.event.inputs.actions == 'android') && github.event.inputs.delivery == true
@@ -174,11 +185,22 @@ jobs:
           whatsNewDirectory: distribution/whatsnew
           mappingFile: GameLife-prod-mapping.txt
 
+      - name: 'Check if upload was successful'
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "PLAYSTORE_STATUS=success" >> $GITHUB_ENV
+            echo "Upload successful, state saved"
+          else
+            echo "PLAYSTORE_STATUS=failure" >> $GITHUB_ENV
+            echo "Upload failed"
+            exit 1
+          fi
+
   build-ios:
     name: '🏗️ Build application 🍏'
     if: github.event.inputs.actions == 'both' || github.event.inputs.actions == 'ios'
     runs-on: macos-latest
-    needs: enable-test-account
+    needs: [ test-client, test-server ]
     steps:
       - name: 'Checkout repository'
         uses: actions/checkout@v4
@@ -267,6 +289,9 @@ jobs:
         env:
           KEYCHAIN_PATH: $RUNNER_TEMP/app-signing.keychain-db
         run: |
+          # Specify the keychain for codesign
+          security default-keychain -s $RUNNER_TEMP/app-signing.keychain-db
+
           # Go to the ios directory
           cd ios
 
@@ -347,17 +372,39 @@ jobs:
 
           # Check if upload was successful
           if [ $? -eq 0 ]; then
-            echo "Upload successful"
+            echo "APPSTORE_STATUS=success" >> $GITHUB_ENV
+            echo "Upload successful, state saved"
           else
+            echo "APPSTORE_STATUS=failure" >> $GITHUB_ENV
             echo "Upload failed"
             exit 1
           fi
 
-  notify-android:
-    name: '📣 Notify Team - App Published 🤖'
-    if: github.event.inputs.actions == 'both' || github.event.inputs.actions == 'android'
+  enable-test-account:
+    name: '🔑 Enable test account'
+    if: success() || failure()
     runs-on: ubuntu-latest
-    needs: delivery-android
+    needs: [ delivery-android, delivery-ios ]
+    steps:
+      - name: 'Checkout'
+        uses: actions/checkout@v4
+
+      - name: 'Install PHP with mysqli extension'
+        run: sudo apt-get update && sudo apt-get install php php-mysqli -y
+
+      - name: 'Enable test account'
+        run: |
+          php ./Tools/Maintenance/setTestAccount.php \
+          '${{ vars.DB_PROD_HOST }}' \
+          '${{ vars.DB_PROD_USER }}' \
+          '${{ secrets.DB_PROD_PASS }}' \
+          '${{ vars.DB_PROD_NAME }}' \
+          1
+
+  notify:
+    name: '📣 App Published'
+    runs-on: ubuntu-latest
+    needs: enable-test-account
     steps:
       - name: 'Checkout repository'
         uses: actions/checkout@v4
@@ -365,7 +412,7 @@ jobs:
       - name: 'Install PHP with mysqli extension'
         run: sudo apt-get update && sudo apt-get install php php-mysqli -y
 
-      - name: 'Get app version'
+      - name: 'Get app version & delivery status'
         run: |
           GL_VERSION=$( \
             php ./Tools/Maintenance/getVersion.php \
@@ -378,51 +425,27 @@ jobs:
           echo "Version: $GL_VERSION"
           echo "GL_VERSION=$GL_VERSION" >> $GITHUB_ENV
 
+          if [[ "$APPSTORE_STATUS" == "success" && "$PLAYSTORE_STATUS" == "success" ]]; then
+            echo "NOTIFICATION_TEXT=GameLife v$GL_VERSION a été envoyée sur le PlayStore 🤖 et l'AppStore 🍏 avec succès 🎉"
+          elif [[ "$APPSTORE_STATUS" == "success" && "$PLAYSTORE_STATUS" == "failure" ]]; then
+            echo "NOTIFICATION_TEXT=GameLife v$GL_VERSION a été envoyée sur l'AppStore 🍏 avec succès 🎉"
+          elif [[ "$APPSTORE_STATUS" == "failure" && "$PLAYSTORE_STATUS" == "success" ]]; then
+            echo "NOTIFICATION_TEXT=GameLife v$GL_VERSION a été envoyée sur le PlayStore 🤖 avec succès 🎉"
+          elif [[ "$APPSTORE_STATUS" == "failure" || "$PLAYSTORE_STATUS" == "failure" ]]; then
+            echo "NOTIFICATION_TEXT=GameLife v$GL_VERSION n'a pas pu être envoyée sur le PlayStore 🤖 ou l'AppStore 🍏"
+          else
+            echo "NOTIFICATION_TEXT=GameLife v$GL_VERSION n'a pas pu être envoyée"
+          fi
+
       - name: 'Send notification to Discord'
         env:
           GL_VERSION: ${{ env.GL_VERSION }}
+          NOTIFICATION_TEXT: ${{ env.NOTIFICATION_TEXT }}
           NEXT_WORKFLOW_URL: 'https://github.com/OxyFoo/GameLife/actions/workflows/prod-deploy.yml'
           DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
         run: |
           curl \
             -H "Content-Type: application/json" \
             -X POST \
-            -d "{\"content\":\"GameLife v$GL_VERSION a été envoyée sur le PlayStore 🤖 avec succès 🎉\n\nPour la valider: <$NEXT_WORKFLOW_URL>\"}" \
-            $DISCORD_WEBHOOK_URL
-
-  notify-ios:
-    name: '📣 Notify Team - App Published 🍏'
-    if: github.event.inputs.actions == 'both' || github.event.inputs.actions == 'ios'
-    runs-on: ubuntu-latest
-    needs: delivery-ios
-    steps:
-      - name: 'Checkout repository'
-        uses: actions/checkout@v4
-
-      - name: 'Install PHP with mysqli extension'
-        run: sudo apt-get update && sudo apt-get install php php-mysqli -y
-
-      - name: 'Get app version'
-        run: |
-          GL_VERSION=$( \
-            php ./Tools/Maintenance/getVersion.php \
-            '${{ vars.DB_TEST_HOST }}' \
-            '${{ vars.DB_TEST_USER }}' \
-            '${{ secrets.DB_TEST_PASS }}' \
-            '${{ vars.DB_TEST_NAME }}' \
-          )
-
-          echo "Version: $GL_VERSION"
-          echo "GL_VERSION=$GL_VERSION" >> $GITHUB_ENV
-
-      - name: 'Send notification to Discord'
-        env:
-          GL_VERSION: ${{ env.GL_VERSION }}
-          NEXT_WORKFLOW_URL: 'https://github.com/OxyFoo/GameLife/actions/workflows/prod-deploy.yml'
-          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
-        run: |
-          curl \
-            -H "Content-Type: application/json" \
-            -X POST \
-            -d "{\"content\":\"GameLife v$GL_VERSION a été envoyée sur l'AppStore 🍏 avec succès 🎉\n\nPour la valider: <$NEXT_WORKFLOW_URL>\"}" \
+            -d "{\"content\":\"$NOTIFICATION_TEXT\",\"embeds\":[{\"title\":\"Workflow\",\"url\":\"$NEXT_WORKFLOW_URL\",\"color\":16711680,\"fields\":[{\"name\":\"Version\",\"value\":\"$GL_VERSION\",\"inline\":true}]}]}" \
             $DISCORD_WEBHOOK_URL
